server:
  port: 8080
  
spring:
  application:
    name: msa-service-coffee-order
  
#Config Server      
  cloud:
    config:
      uri: http://localhost:8888 
      name: msa-architecture-config-server
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

#spring reload
  thymeleaf:
    cache: false    
  devtools:
    livereload:
      enabled: true
      
#Eureka Client   
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9091/eureka/

